export const playerList = {
    teams: [
        {
            team_name: 'Chennai Super Kings',
            players: [
                { name: 'Ruturaj Gaikwad', role: 'BAT' },
                { name: 'Ravindra Jadeja', role: 'AR' },
                { name: 'Matheesha Pathirana', role: 'BOWL' },
                { name: 'Shivam Dube', role: 'AR' },
                { name: 'Noor Ahmad', role: 'BOWL' },
                { name: 'Ravichandran Ashwin', role: 'AR' },
                { name: 'Devon Conway', role: 'BAT' },
                { name: 'Khaleel Ahmed', role: 'BOWL' },
                { name: 'Rachin Ravindra', role: 'AR' },
                { name: 'MS Dhoni', role: 'BAT' },
                { name: 'Anshul Kamboj', role: 'AR' },
                { name: 'Rahul Tripathi', role: 'BAT' },
                { name: 'Sam Curran', role: 'AR' },
                { name: 'Gurjapneet Singh', role: 'BOWL' },
                { name: 'Nathan Ellis', role: 'BOWL' },
                { name: 'Deepak Hooda', role: 'AR' },
                { name: 'Jamie Overton', role: 'AR' },
                { name: 'Vijay Shankar', role: 'AR' },
                { name: 'Vansh Bedi', role: 'BAT' },
                { name: 'C Andre Siddarth', role: 'BAT' },
                { name: 'Ramakrishna Ghosh', role: 'AR' },
                { name: 'Shaik Rasheed', role: 'BAT' },
                { name: 'Mukesh Choudhary', role: 'BOWL' },
                { name: 'Kamlesh Nagarkoti', role: 'AR' },
                { name: 'Shreyas Gopal', role: 'BOWL' },
            ],
        },
        {
            team_name: 'Delhi Capitals',
            players: [
                { name: 'Axar Patel', role: 'AR' },
                { name: 'KL Rahul', role: 'BAT' },
                { name: 'Kuldeep Yadav', role: 'BOWL' },
                { name: 'Mitchell Starc', role: 'BOWL' },
                { name: 'T Natarajan', role: 'BOWL' },
                { name: 'Tristan Stubbs', role: 'BAT' },
                { name: 'Jake Fraser-McGurk', role: 'BAT' },
                { name: 'Mukesh Kumar', role: 'BOWL' },
                { name: 'Harry Brook', role: 'BAT' },
                { name: 'Abishek Porel', role: 'BAT' },
                { name: 'Ashutosh Sharma', role: 'AR' },
                { name: 'Mohit Sharma', role: 'BOWL' },
                { name: 'Faf du Plessis', role: 'BAT' },
                { name: 'Sameer Rizvi', role: 'AR' },
                { name: 'Donovan Ferreira', role: 'BAT' },
                { name: 'Dushmantha Chameera', role: 'BOWL' },
                { name: 'Vipraj Nigam', role: 'AR' },
                { name: 'Karun Nair', role: 'BAT' },
                { name: 'Madhav Tiwari', role: 'AR' },
                { name: 'Manvanth Kumar', role: 'AR' },
                { name: 'Tripurana Vijay', role: 'AR' },
                { name: 'Darshan Nalkande', role: 'AR' },
                { name: 'Ajay Mandal', role: 'AR' },
            ],
        },
        {
            team_name: 'Gujarat Titans',
            players: [
                { name: 'Rashid Khan', role: 'BOWL' },
                { name: 'Shubman Gill', role: 'BAT' },
                { name: 'Jos Buttler', role: 'BAT' },
                { name: 'Mohammed Siraj', role: 'BOWL' },
                { name: 'Kagiso Rabada', role: 'BOWL' },
                { name: 'Prasidh Krishna', role: 'BOWL' },
                { name: 'Sai Sudharsan', role: 'AR' },
                { name: 'M Shahrukh Khan', role: 'AR' },
                { name: 'Rahul Tewatia', role: 'AR' },
                { name: 'Washington Sundar', role: 'AR' },
                { name: 'Sherfane Rutherford', role: 'BAT' },
                { name: 'Gerald Coetzee', role: 'BOWL' },
                { name: 'Sai Kishore', role: 'AR' },
                { name: 'Glenn Phillips', role: 'BAT' },
                { name: 'Mahipal Lomror', role: 'AR' },
                { name: 'Gurnoor Brar', role: 'BOWL' },
                { name: 'Arshad Khan', role: 'AR' },
                { name: 'Karim Janat', role: 'AR' },
                { name: 'Jayant Yadav', role: 'AR' },
                { name: 'Ishant Sharma', role: 'BOWL' },
                { name: 'Kumar Kushagra', role: 'BAT' },
                { name: 'Nishant Sindhu', role: 'AR' },
                { name: 'Manav Suthar', role: 'BOWL' },
                { name: 'Anuj Rawat', role: 'BAT' },
                { name: 'Kulwant Khejroliya', role: 'BOWL' },
            ],
        },
        {
            team_name: 'Kolkata Knight Riders',
            players: [
                { name: 'Venkatesh Iyer', role: 'AR' },
                { name: 'Rinku Singh', role: 'BAT' },
                { name: 'Varun Chakravarthy', role: 'AR' },
                { name: 'Andre Russell', role: 'AR' },
                { name: 'Sunil Narine', role: 'BOWL' },
                { name: 'Anrich Nortje', role: 'BOWL' },
                { name: 'Harshit Rana', role: 'BOWL' },
                { name: 'Ramandeep Singh', role: 'AR' },
                { name: 'Quinton de Kock', role: 'BAT' },
                { name: 'Angkrish Raghuvanshi', role: 'BAT' },
                { name: 'Spencer Johnson', role: 'BOWL' },
                { name: 'Rahmanullah Gurbaz', role: 'BAT' },
                { name: 'Moeen Ali', role: 'AR' },
                { name: 'Vaibhav Arora', role: 'BOWL' },
                { name: 'Rovman Powell', role: 'BAT' },
                { name: 'Ajinkya Rahane', role: 'BAT' },
                { name: 'Umran Malik', role: 'BOWL' },
                { name: 'Manish Pandey', role: 'BAT' },
                { name: 'Anukul Roy', role: 'AR' },
                { name: 'Luvnith Sisodia', role: 'BAT' },
                { name: 'Mayank Markande', role: 'BOWL' },
            ],
        },
        {
            team_name: 'Lucknow Super Giants',
            players: [
                { name: 'Rishabh Pant', role: 'BAT' },
                { name: 'Nicholas Pooran', role: 'BAT' },
                { name: 'Mayank Yadav', role: 'BOWL' },
                { name: 'Ravi Bishnoi', role: 'BOWL' },
                { name: 'Avesh Khan', role: 'BOWL' },
                { name: 'Akash Deep', role: 'BOWL' },
                { name: 'David Miller', role: 'BAT' },
                { name: 'Abdul Samad', role: 'AR' },
                { name: 'Ayush Badoni', role: 'AR' },
                { name: 'Mohsin Khan', role: 'BOWL' },
                { name: 'Mitchell Marsh', role: 'AR' },
                { name: 'Shahbaz Ahmed', role: 'AR' },
                { name: 'Aiden Markram', role: 'BAT' },
                { name: 'Shamar Joseph', role: 'BOWL' },
                { name: 'Manimaran Siddharth', role: 'BOWL' },
                { name: 'Matthew Breetzke', role: 'BAT' },
                { name: 'Digvesh Rathi', role: 'BOWL' },
                { name: 'Arshin Kulkarni', role: 'AR' },
                { name: 'Prince Yadav', role: 'BOWL' },
                { name: 'Yuvraj Chaudhary', role: 'AR' },
                { name: 'Akash Singh', role: 'BOWL' },
                { name: 'Rajvardhan Hangargekar', role: 'AR' },
                { name: 'Aryan Juyal', role: 'BAT' },
                { name: 'Himmat Singh', role: 'BAT' },
            ],
        },
        {
            team_name: 'Mumbai Indians',
            players: [
                { name: 'Jasprit Bumrah', role: 'BOWL' },
                { name: 'Hardik Pandya', role: 'AR' },
                { name: 'Suryakumar Yadav', role: 'BAT' },
                { name: 'Rohit Sharma', role: 'BAT' },
                { name: 'Trent Boult', role: 'BOWL' },
                { name: 'Deepak Chahar', role: 'BOWL' },
                { name: 'Tilak Varma', role: 'AR' },
                { name: 'Naman Dhir', role: 'AR' },
                { name: 'Will Jacks', role: 'AR' },
                { name: 'AM Ghazanfar', role: 'BOWL' },
                { name: 'Mitchell Santner', role: 'AR' },
                { name: 'Ryan Rickelton', role: 'BAT' },
                { name: 'Reece Topley', role: 'BOWL' },
                { name: 'Lizaad Williams', role: 'BOWL' },
                { name: 'Robin Minz', role: 'BAT' },
                { name: 'Karn Sharma', role: 'BOWL' },
                { name: 'Vignesh Puthur', role: 'AR' },
                { name: 'Bevon Jacobs', role: 'BAT' },
                { name: 'Satyanarayana Raju', role: 'BOWL' },
                { name: 'Raj Bawa', role: 'AR' },
                { name: 'Ashwani Kumar', role: 'BOWL' },
                { name: 'Arjun Tendulkar', role: 'BOWL' },
                { name: 'Krishnan Shrijith', role: 'BAT' },
            ],
        },
        {
            team_name: 'Punjab Kings',
            players: [
                { name: 'Shreyas Iyer', role: 'BAT' },
                { name: 'Arshdeep Singh', role: 'BOWL' },
                { name: 'Yuzvendra Chahal', role: 'BOWL' },
                { name: 'Marcus Stoinis', role: 'AR' },
                { name: 'Marco Jansen', role: 'AR' },
                { name: 'Shashank Singh', role: 'AR' },
                { name: 'Nehal Wadhera', role: 'BAT' },
                { name: 'Glenn Maxwell', role: 'AR' },
                { name: 'Prabhsimran Singh', role: 'BAT' },
                { name: 'Priyansh Arya', role: 'AR' },
                { name: 'Josh Inglis', role: 'BAT' },
                { name: 'Azmatullah Omarzai', role: 'AR' },
                { name: 'Lockie Ferguson', role: 'BOWL' },
                { name: 'Vijaykumar Vyshak', role: 'BOWL' },
                { name: 'Yash Thakur', role: 'BOWL' },
                { name: 'Harpreet Brar', role: 'AR' },
                { name: 'Aaron Hardie', role: 'AR' },
                { name: 'Vishnu Vinod', role: 'BAT' },
                { name: 'Kuldeep Sen', role: 'BOWL' },
                { name: 'Xavier Bartlett', role: 'BOWL' },
                { name: 'Suryansh Shedge', role: 'AR' },
                { name: 'Pyla Avinash', role: 'BAT' },
                { name: 'Musheer Khan', role: 'AR' },
                { name: 'Harnoor Singh', role: 'BAT' },
                { name: 'Praveen Dubey', role: 'AR' },
            ],
        },
        {
            team_name: 'Rajasthan Royals',
            players: [
                { name: 'Yashasvi Jaiswal', role: 'AR' },
                { name: 'Sanju Samson', role: 'BAT' },
                { name: 'Dhruv Jurel', role: 'BAT' },
                { name: 'Riyan Parag', role: 'AR' },
                { name: 'Jofra Archer', role: 'BOWL' },
                { name: 'Shimron Hetmyer', role: 'BAT' },
                { name: 'Tushar Deshpande', role: 'BOWL' },
                { name: 'Wanindu Hasaranga', role: 'BOWL' },
                { name: 'Maheesh Theekshana', role: 'BOWL' },
                { name: 'Nitish Rana', role: 'AR' },
                { name: 'Sandeep Sharma', role: 'BOWL' },
                { name: 'Fazalhaq Farooqi', role: 'BOWL' },
                { name: 'Kwena Maphaka', role: 'BOWL' },
                { name: 'Akash Madhwal', role: 'BOWL' },
                { name: 'Vaibhav Suryavanshi', role: 'BAT' },
                { name: 'Shubham Dubey', role: 'BAT' },
                { name: 'Yudhvir Singh', role: 'AR' },
                { name: 'Kunal Singh Rathore', role: 'BAT' },
                { name: 'Ashok Sharma', role: 'BOWL' },
                { name: 'Kumar Kartikeya', role: 'BOWL' },
            ],
        },
        {
            team_name: 'Royal Challengers Bengaluru',
            players: [
                { name: 'Virat Kohli', role: 'BAT' },
                { name: 'Josh Hazlewood', role: 'BOWL' },
                { name: 'Phil Salt', role: 'BAT' },
                { name: 'Rajat Patidar', role: 'BAT' },
                { name: 'Jitesh Sharma', role: 'BAT' },
                { name: 'Bhuvneshwar Kumar', role: 'BOWL' },
                { name: 'Liam Livingstone', role: 'AR' },
                { name: 'Rasikh Salam', role: 'BOWL' },
                { name: 'Krunal Pandya', role: 'AR' },
                { name: 'Yash Dayal', role: 'BOWL' },
                { name: 'Tim David', role: 'AR' },
                { name: 'Suyash Sharma', role: 'BOWL' },
                { name: 'Jacob Bethell', role: 'AR' },
                { name: 'Devdutt Padikkal', role: 'BAT' },
                { name: 'Nuwan Thushara', role: 'BOWL' },
                { name: 'Romario Shepherd', role: 'AR' },
                { name: 'Lungi Ngidi', role: 'BOWL' },
                { name: 'Swapnil Singh', role: 'AR' },
                { name: 'Abhinandan Singh', role: 'BOWL' },
                { name: 'Swastik Chikara', role: 'BAT' },
                { name: 'Mohit Rathee', role: 'BOWL' },
                { name: 'Manoj Bhandage', role: 'AR' },
            ],
        },
        {
            team_name: 'Sunrisers Hyderabad',
            players: [
                { name: 'Heinrich Klaasen', role: 'BAT' },
                { name: 'Pat Cummins', role: 'AR' },
                { name: 'Abhishek Sharma', role: 'AR' },
                { name: 'Travis Head', role: 'BAT' },
                { name: 'Ishan Kishan', role: 'BAT' },
                { name: 'Mohammed Shami', role: 'BOWL' },
                { name: 'Harshal Patel', role: 'AR' },
                { name: 'Nitish Kumar Reddy', role: 'AR' },
                { name: 'Rahul Chahar', role: 'BOWL' },
                { name: 'Abhinav Manohar', role: 'BAT' },
                { name: 'Adam Zampa', role: 'BOWL' },
                { name: 'Simarjeet Singh', role: 'BOWL' },
                { name: 'Eshan Malinga', role: 'BOWL' },
                { name: 'Brydon Carse', role: 'AR' },
                { name: 'Jaydev Unadkat', role: 'BOWL' },
                { name: 'Kamindu Mendis', role: 'AR' },
                { name: 'Zeeshan Ansari', role: 'BOWL' },
                { name: 'Aniket Verma', role: 'BAT' },
                { name: 'Atharva Taide', role: 'BAT' },
                { name: 'Sachin Baby', role: 'BAT' },
            ],
        },
    ],
};
