export const teamSchedule = [
    {
        MatchNumber: 1,
        DateUtc: '2025-03-22 14:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'Kolkata Knight Riders',
        AwayTeam: 'Royal Challengers Bengaluru',
    },
    {
        MatchNumber: 2,
        DateUtc: '2025-03-23 10:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'Sunrisers Hyderabad',
        AwayTeam: 'Rajasthan Royals',
    },
    {
        MatchNumber: 3,
        DateUtc: '2025-03-23 14:00:00Z',
        Location: 'MA Chidambaram Stadium',
        HomeTeam: 'Chennai Super Kings',
        AwayTeam: 'Mumbai Indians',
    },
    {
        MatchNumber: 4,
        DateUtc: '2025-03-24 14:00:00Z',
        Location: 'Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium',
        HomeTeam: 'Delhi Capitals',
        AwayTeam: 'Lucknow Super Giants',
    },
    {
        MatchNumber: 5,
        DateUtc: '2025-03-25 14:00:00Z',
        Location: 'Narendra Modi Stadium',
        HomeTeam: 'Gujarat Titans',
        AwayTeam: 'Punjab Kings',
    },
    {
        MatchNumber: 6,
        DateUtc: '2025-03-26 14:00:00Z',
        Location: 'Barsapara Cricket Stadium',
        HomeTeam: 'Rajasthan Royals',
        AwayTeam: 'Kolkata Knight Riders',
    },
    {
        MatchNumber: 7,
        DateUtc: '2025-03-27 14:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'Sunrisers Hyderabad',
        AwayTeam: 'Lucknow Super Giants',
    },
    {
        MatchNumber: 8,
        DateUtc: '2025-03-28 14:00:00Z',
        Location: 'MA Chidambaram Stadium',
        HomeTeam: 'Chennai Super Kings',
        AwayTeam: 'Royal Challengers Bengaluru',
    },
    {
        MatchNumber: 9,
        DateUtc: '2025-03-29 14:00:00Z',
        Location: 'Narendra Modi Stadium',
        HomeTeam: 'Gujarat Titans',
        AwayTeam: 'Mumbai Indians',
    },
    {
        MatchNumber: 10,
        DateUtc: '2025-03-30 10:00:00Z',
        Location: 'Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium',
        HomeTeam: 'Delhi Capitals',
        AwayTeam: 'Sunrisers Hyderabad',
    },
    {
        MatchNumber: 11,
        DateUtc: '2025-03-30 14:00:00Z',
        Location: 'Barsapara Cricket Stadium',
        HomeTeam: 'Rajasthan Royals',
        AwayTeam: 'Chennai Super Kings',
    },
    {
        MatchNumber: 12,
        DateUtc: '2025-03-31 14:00:00Z',
        Location: 'Wankhede Stadium',
        HomeTeam: 'Mumbai Indians',
        AwayTeam: 'Kolkata Knight Riders',
    },
    {
        MatchNumber: 13,
        DateUtc: '2025-04-01 14:00:00Z',
        Location: 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Crick',
        HomeTeam: 'Lucknow Super Giants',
        AwayTeam: 'Punjab Kings',
    },
    {
        MatchNumber: 14,
        DateUtc: '2025-04-02 14:00:00Z',
        Location: 'M Chinnaswamy Stadium',
        HomeTeam: 'Royal Challengers Bengaluru',
        AwayTeam: 'Gujarat Titans',
    },
    {
        MatchNumber: 15,
        DateUtc: '2025-04-03 14:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'Kolkata Knight Riders',
        AwayTeam: 'Sunrisers Hyderabad',
    },
    {
        MatchNumber: 16,
        DateUtc: '2025-04-04 14:00:00Z',
        Location: 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Crick',
        HomeTeam: 'Lucknow Super Giants',
        AwayTeam: 'Mumbai Indians',
    },
    {
        MatchNumber: 17,
        DateUtc: '2025-04-05 10:00:00Z',
        Location: 'MA Chidambaram Stadium',
        HomeTeam: 'Chennai Super Kings',
        AwayTeam: 'Delhi Capitals',
    },
    {
        MatchNumber: 18,
        DateUtc: '2025-04-05 14:00:00Z',
        Location: 'New PCA Stadium',
        HomeTeam: 'Punjab Kings',
        AwayTeam: 'Rajasthan Royals',
    },
    {
        MatchNumber: 19,
        DateUtc: '2025-04-06 10:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'Kolkata Knight Riders',
        AwayTeam: 'Lucknow Super Giants',
    },
    {
        MatchNumber: 20,
        DateUtc: '2025-04-06 14:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'Sunrisers Hyderabad',
        AwayTeam: 'Gujarat Titans',
    },
    {
        MatchNumber: 21,
        DateUtc: '2025-04-07 14:00:00Z',
        Location: 'Wankhede Stadium',
        HomeTeam: 'Mumbai Indians',
        AwayTeam: 'Royal Challengers Bengaluru',
    },
    {
        MatchNumber: 22,
        DateUtc: '2025-04-08 14:00:00Z',
        Location: 'New PCA Stadium',
        HomeTeam: 'Punjab Kings',
        AwayTeam: 'Chennai Super Kings',
    },
    {
        MatchNumber: 23,
        DateUtc: '2025-04-09 14:00:00Z',
        Location: 'Narendra Modi Stadium',
        HomeTeam: 'Gujarat Titans',
        AwayTeam: 'Rajasthan Royals',
    },
    {
        MatchNumber: 24,
        DateUtc: '2025-04-10 14:00:00Z',
        Location: 'M Chinnaswamy Stadium',
        HomeTeam: 'Royal Challengers Bengaluru',
        AwayTeam: 'Delhi Capitals',
    },
    {
        MatchNumber: 25,
        DateUtc: '2025-04-11 14:00:00Z',
        Location: 'MA Chidambaram Stadium',
        HomeTeam: 'Chennai Super Kings',
        AwayTeam: 'Kolkata Knight Riders',
    },
    {
        MatchNumber: 26,
        DateUtc: '2025-04-12 10:00:00Z',
        Location: 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Crick',
        HomeTeam: 'Lucknow Super Giants',
        AwayTeam: 'Gujarat Titans',
    },
    {
        MatchNumber: 27,
        DateUtc: '2025-04-12 14:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'Sunrisers Hyderabad',
        AwayTeam: 'Punjab Kings',
    },
    {
        MatchNumber: 28,
        DateUtc: '2025-04-13 10:00:00Z',
        Location: 'Sawai Mansingh Stadium',
        HomeTeam: 'Rajasthan Royals',
        AwayTeam: 'Royal Challengers Bengaluru',
    },
    {
        MatchNumber: 29,
        DateUtc: '2025-04-13 14:00:00Z',
        Location: 'Arun Jaitley Stadium',
        HomeTeam: 'Delhi Capitals',
        AwayTeam: 'Mumbai Indians',
    },
    {
        MatchNumber: 30,
        DateUtc: '2025-04-14 14:00:00Z',
        Location: 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Crick',
        HomeTeam: 'Lucknow Super Giants',
        AwayTeam: 'Chennai Super Kings',
    },
    {
        MatchNumber: 31,
        DateUtc: '2025-04-15 14:00:00Z',
        Location: 'New PCA Stadium',
        HomeTeam: 'Punjab Kings',
        AwayTeam: 'Kolkata Knight Riders',
    },
    {
        MatchNumber: 32,
        DateUtc: '2025-04-16 14:00:00Z',
        Location: 'Arun Jaitley Stadium',
        HomeTeam: 'Delhi Capitals',
        AwayTeam: 'Rajasthan Royals',
    },
    {
        MatchNumber: 33,
        DateUtc: '2025-04-17 14:00:00Z',
        Location: 'Wankhede Stadium',
        HomeTeam: 'Mumbai Indians',
        AwayTeam: 'Sunrisers Hyderabad',
    },
    {
        MatchNumber: 34,
        DateUtc: '2025-04-18 14:00:00Z',
        Location: 'M Chinnaswamy Stadium',
        HomeTeam: 'Royal Challengers Bengaluru',
        AwayTeam: 'Punjab Kings',
    },
    {
        MatchNumber: 35,
        DateUtc: '2025-04-19 10:00:00Z',
        Location: 'Narendra Modi Stadium',
        HomeTeam: 'Gujarat Titans',
        AwayTeam: 'Delhi Capitals',
    },
    {
        MatchNumber: 36,
        DateUtc: '2025-04-19 14:00:00Z',
        Location: 'Sawai Mansingh Stadium',
        HomeTeam: 'Rajasthan Royals',
        AwayTeam: 'Lucknow Super Giants',
    },
    {
        MatchNumber: 37,
        DateUtc: '2025-04-20 10:00:00Z',
        Location: 'New PCA Stadium',
        HomeTeam: 'Punjab Kings',
        AwayTeam: 'Royal Challengers Bengaluru',
    },
    {
        MatchNumber: 38,
        DateUtc: '2025-04-20 14:00:00Z',
        Location: 'Wankhede Stadium',
        HomeTeam: 'Mumbai Indians',
        AwayTeam: 'Chennai Super Kings',
    },
    {
        MatchNumber: 39,
        DateUtc: '2025-04-21 14:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'Kolkata Knight Riders',
        AwayTeam: 'Gujarat Titans',
    },
    {
        MatchNumber: 40,
        DateUtc: '2025-04-22 14:00:00Z',
        Location: 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Crick',
        HomeTeam: 'Lucknow Super Giants',
        AwayTeam: 'Delhi Capitals',
    },
    {
        MatchNumber: 41,
        DateUtc: '2025-04-23 14:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'Sunrisers Hyderabad',
        AwayTeam: 'Mumbai Indians',
    },
    {
        MatchNumber: 42,
        DateUtc: '2025-04-24 14:00:00Z',
        Location: 'M Chinnaswamy Stadium',
        HomeTeam: 'Royal Challengers Bengaluru',
        AwayTeam: 'Rajasthan Royals',
    },
    {
        MatchNumber: 43,
        DateUtc: '2025-04-25 14:00:00Z',
        Location: 'MA Chidambaram Stadium',
        HomeTeam: 'Chennai Super Kings',
        AwayTeam: 'Sunrisers Hyderabad',
    },
    {
        MatchNumber: 44,
        DateUtc: '2025-04-26 14:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'Kolkata Knight Riders',
        AwayTeam: 'Punjab Kings',
    },
    {
        MatchNumber: 45,
        DateUtc: '2025-04-27 10:00:00Z',
        Location: 'Wankhede Stadium',
        HomeTeam: 'Mumbai Indians',
        AwayTeam: 'Lucknow Super Giants',
    },
    {
        MatchNumber: 46,
        DateUtc: '2025-04-27 14:00:00Z',
        Location: 'Arun Jaitley Stadium',
        HomeTeam: 'Delhi Capitals',
        AwayTeam: 'Royal Challengers Bengaluru',
    },
    {
        MatchNumber: 47,
        DateUtc: '2025-04-28 14:00:00Z',
        Location: 'Sawai Mansingh Stadium',
        HomeTeam: 'Rajasthan Royals',
        AwayTeam: 'Gujarat Titans',
    },
    {
        MatchNumber: 48,
        DateUtc: '2025-04-29 14:00:00Z',
        Location: 'Arun Jaitley Stadium',
        HomeTeam: 'Delhi Capitals',
        AwayTeam: 'Kolkata Knight Riders',
    },
    {
        MatchNumber: 49,
        DateUtc: '2025-04-30 14:00:00Z',
        Location: 'MA Chidambaram Stadium',
        HomeTeam: 'Chennai Super Kings',
        AwayTeam: 'Punjab Kings',
    },
    {
        MatchNumber: 50,
        DateUtc: '2025-05-01 14:00:00Z',
        Location: 'Sawai Mansingh Stadium',
        HomeTeam: 'Rajasthan Royals',
        AwayTeam: 'Mumbai Indians',
    },
    {
        MatchNumber: 51,
        DateUtc: '2025-05-02 14:00:00Z',
        Location: 'Narendra Modi Stadium',
        HomeTeam: 'Gujarat Titans',
        AwayTeam: 'Sunrisers Hyderabad',
    },
    {
        MatchNumber: 52,
        DateUtc: '2025-05-03 14:00:00Z',
        Location: 'M Chinnaswamy Stadium',
        HomeTeam: 'Royal Challengers Bengaluru',
        AwayTeam: 'Chennai Super Kings',
    },
    {
        MatchNumber: 53,
        DateUtc: '2025-05-04 10:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'Kolkata Knight Riders',
        AwayTeam: 'Rajasthan Royals',
    },
    {
        MatchNumber: 54,
        DateUtc: '2025-05-04 14:00:00Z',
        Location: 'Himachal Pradesh Cricket Association Stadium',
        HomeTeam: 'Punjab Kings',
        AwayTeam: 'Lucknow Super Giants',
    },
    {
        MatchNumber: 55,
        DateUtc: '2025-05-05 14:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'Sunrisers Hyderabad',
        AwayTeam: 'Delhi Capitals',
    },
    {
        MatchNumber: 56,
        DateUtc: '2025-05-06 14:00:00Z',
        Location: 'Wankhede Stadium',
        HomeTeam: 'Mumbai Indians',
        AwayTeam: 'Gujarat Titans',
    },
    {
        MatchNumber: 57,
        DateUtc: '2025-05-07 14:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'Kolkata Knight Riders',
        AwayTeam: 'Chennai Super Kings',
    },
    {
        MatchNumber: 58,
        DateUtc: '2025-05-08 14:00:00Z',
        Location: 'Himachal Pradesh Cricket Association Stadium',
        HomeTeam: 'Punjab Kings',
        AwayTeam: 'Delhi Capitals',
    },
    {
        MatchNumber: 59,
        DateUtc: '2025-05-09 14:00:00Z',
        Location: 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Crick',
        HomeTeam: 'Lucknow Super Giants',
        AwayTeam: 'Royal Challengers Bengaluru',
    },
    {
        MatchNumber: 60,
        DateUtc: '2025-05-10 14:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'Sunrisers Hyderabad',
        AwayTeam: 'Kolkata Knight Riders',
    },
    {
        MatchNumber: 61,
        DateUtc: '2025-05-11 10:00:00Z',
        Location: 'Himachal Pradesh Cricket Association Stadium',
        HomeTeam: 'Punjab Kings',
        AwayTeam: 'Mumbai Indians',
    },
    {
        MatchNumber: 62,
        DateUtc: '2025-05-11 14:00:00Z',
        Location: 'Arun Jaitley Stadium',
        HomeTeam: 'Delhi Capitals',
        AwayTeam: 'Gujarat Titans',
    },
    {
        MatchNumber: 63,
        DateUtc: '2025-05-12 14:00:00Z',
        Location: 'MA Chidambaram Stadium',
        HomeTeam: 'Chennai Super Kings',
        AwayTeam: 'Rajasthan Royals',
    },
    {
        MatchNumber: 64,
        DateUtc: '2025-05-13 14:00:00Z',
        Location: 'M Chinnaswamy Stadium',
        HomeTeam: 'Royal Challengers Bengaluru',
        AwayTeam: 'Sunrisers Hyderabad',
    },
    {
        MatchNumber: 65,
        DateUtc: '2025-05-14 14:00:00Z',
        Location: 'Narendra Modi Stadium',
        HomeTeam: 'Gujarat Titans',
        AwayTeam: 'Lucknow Super Giants',
    },
    {
        MatchNumber: 66,
        DateUtc: '2025-05-15 14:00:00Z',
        Location: 'Wankhede Stadium',
        HomeTeam: 'Mumbai Indians',
        AwayTeam: 'Delhi Capitals',
    },
    {
        MatchNumber: 67,
        DateUtc: '2025-05-16 14:00:00Z',
        Location: 'Sawai Mansingh Stadium',
        HomeTeam: 'Rajasthan Royals',
        AwayTeam: 'Punjab Kings',
    },
    {
        MatchNumber: 68,
        DateUtc: '2025-05-17 14:00:00Z',
        Location: 'M Chinnaswamy Stadium',
        HomeTeam: 'Royal Challengers Bengaluru',
        AwayTeam: 'Kolkata Knight Riders',
    },
    {
        MatchNumber: 69,
        DateUtc: '2025-05-18 10:00:00Z',
        Location: 'Narendra Modi Stadium',
        HomeTeam: 'Gujarat Titans',
        AwayTeam: 'Chennai Super Kings',
    },
    {
        MatchNumber: 70,
        DateUtc: '2025-05-18 14:00:00Z',
        Location: 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Crick',
        HomeTeam: 'Lucknow Super Giants',
        AwayTeam: 'Sunrisers Hyderabad',
    },
    {
        MatchNumber: 71,
        DateUtc: '2025-05-20 14:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'To be announced',
        AwayTeam: 'To be announced',
    },
    {
        MatchNumber: 72,
        DateUtc: '2025-05-21 14:00:00Z',
        Location: 'Rajiv Gandhi International Stadium',
        HomeTeam: 'To be announced',
        AwayTeam: 'To be announced',
    },
    {
        MatchNumber: 73,

        DateUtc: '2025-05-23 14:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'To be announced',
        AwayTeam: 'To be announced',
    },
    {
        MatchNumber: 74,

        DateUtc: '2025-05-25 14:00:00Z',
        Location: 'Eden Gardens',
        HomeTeam: 'To be announced',
        AwayTeam: 'To be announced',
    },
];
